# Generated by Django 4.2.3 on 2023-07-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_like_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
