# Generated by Django 4.2.3 on 2023-08-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_image_postimage_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
