# Generated by Django 4.2.3 on 2023-08-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_images_alter_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
